### PR TITLE
Use single baseline in Morganey thumbnail

### PR DESCRIPTION
**Pull request by Minoru**
Morganey logo (`λ o.o`) and `EPISODE_NUMBER` had different baselines, which is, visually, a bit jarring. I moved both pieces of text onto a single baseline and then centred it all vertically.

### CODE REVIEW

**Review by rexim — DISMISSED** [review]

**Comment by rexim** [comment]
@Minoru, alright, I assume that we got the same result when exported svg to png. I know exactly why I don't like the new variant. This is because I don't see `(λ o.o)` as text. I see it as picture. The picture of a lambda guy, who's the logo of the Morganey programming language. And I simply centered the `EPISODE_NUMBER` to the center line of that picture. Here is comparison (left is mine, right is yours):

compare

I'm gonna decline this PR, sorry. Nothing personal. All of this stuff is really subjective. And I subjectively like my variant better, because I see it that way. Thanks for the PR anyway! It made me analyze my approach which is good. :)

P.S. let me know if you got a different result after converting svg to png, we may easily talk about different things.

**Comment by Minoru** [comment]
> I'm gonna decline this PR, sorry. Nothing personal. All of this stuff is really subjective.

It's okay. I understand.

But there's some rules in art, too, so I'll try to argue that the problem exists, even if matching baselines is not a solution.

> This is because I don't see (λ o.o) as text. I see it as picture. The picture of a lambda guy[…]. And I simply centered the EPISODE_NUMBER to the center line of that picture.

Oh, okay. That indeed makes my changes inappropriate.

I think my _real_ problem with current alignment is that it's _arbitrary_. Logo and text form a single composition, but they have different everything: font size, color, vertical position (I didn't realize they were linked by centre line until you told me).

How about making the text larger to match picture's height? That should help people read `(λ o.o)` as picture, too.

**Comment by rexim** [comment]
> How about making the text larger to match picture's height? That should help people read `(λ o.o)` as picture, too.

Could you please show me what you mean? Just push that to this PR if possible.

**Comment by Minoru** [comment]
Just a quick and dirty edit. I'll try to clean the code up later if you like the result.

**Comment by rexim** [comment]
@Minoru nope, it's too large. I'm really sorry! :( Thanks for spending your time on that anyway!

**Pull request closed without merging**
